ALTER EXTERNAL TABLE BRONZE_DB.SALESFORCE.PRODUCT_CATALOG_EXT REFRESH;
ALTER EXTERNAL TABLE BRONZE_DB.SALESFORCE.SALES_REP_MASTER_EXT REFRESH;
ALTER EXTERNAL TABLE BRONZE_DB.SALESFORCE.ACCOUNT_MASTER_EXT REFRESH;
ALTER PIPE BRONZE_DB.SALESFORCE.PIPE_SALES_ORDERS REFRESH;