CREATE OR REPLACE STORAGE INTEGRATION S3_INTEGRATION_SALESFORCE
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_ALLOWED_LOCATIONS = ('s3://file-saleforce-test-s3/')
  STORAGE_AWS_ROLE_ARN = 'role_arn';

DESC STORAGE INTEGRATION S3_INTEGRATION_SALESFORCE;


CREATE OR REPLACE FILE FORMAT BRONZE_DB.SALESFORCE.CSV_FORMAT_SALESFORCE
  TYPE = 'CSV'
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  NULL_IF = ('NULL', 'null')
  EMPTY_FIELD_AS_NULL = TRUE;

CREATE OR REPLACE STAGE BRONZE_DB.SALESFORCE.ST_S3_SALESFORCE
  URL = 's3://file-saleforce-test-s3/' 
  STORAGE_INTEGRATION = S3_INTEGRATION_SALESFORCE 
  FILE_FORMAT = BRONZE_DB.SALESFORCE.CSV_FORMAT_SALESFORCE;

  -------- EXTERNAL TABLES TO DIMENSIONS --------

  CREATE OR REPLACE EXTERNAL TABLE BRONZE_DB.SALESFORCE.ACCOUNT_MASTER_EXT (
    account_id STRING AS (value:c1::string),
    account_name STRING AS (value:c2::string),
    industry STRING AS (value:c3::string),
    customer_segment STRING AS (value:c4::string)
)
WITH LOCATION = @BRONZE_DB.SALESFORCE.ST_S3_SALESFORCE/account_master/
FILE_FORMAT = BRONZE_DB.SALESFORCE.CSV_FORMAT_SALESFORCE;

CREATE OR REPLACE EXTERNAL TABLE BRONZE_DB.SALESFORCE.PRODUCT_CATALOG_EXT (
    PRODUCT_ID VARCHAR AS (value:c1::varchar),
    PRODUCT_NAME VARCHAR AS (value:c2::varchar),
    PRODUCT_FAMILY VARCHAR AS (value:c3::varchar),
    LIST_PRICE FLOAT AS (value:c4::float)
)
WITH LOCATION = @BRONZE_DB.SALESFORCE.ST_S3_SALESFORCE/product_catalog/
FILE_FORMAT = BRONZE_DB.SALESFORCE.CSV_FORMAT_SALESFORCE;

CREATE OR REPLACE EXTERNAL TABLE BRONZE_DB.SALESFORCE.SALES_REP_MASTER_EXT (
    SALES_REP_ID VARCHAR AS (value:c1::varchar),
    REP_NAME VARCHAR AS (value:c2::varchar),
    MANAGER_NAME VARCHAR AS (value:c3::varchar),
    TERRITORY VARCHAR AS (value:c4::varchar),
    HIRE_DATE DATE AS (value:c5::date)
)
WITH LOCATION = @BRONZE_DB.SALESFORCE.ST_S3_SALESFORCE/sales_rep_master/
FILE_FORMAT = BRONZE_DB.SALESFORCE.CSV_FORMAT_SALESFORCE;

----- PIPE FOR SALES ORDERS ------
CREATE OR REPLACE TABLE BRONZE_DB.SALESFORCE.SALES_ORDERS (
    ORDER_ID VARCHAR,
    OPPORTUNITY_ID VARCHAR,
    ACCOUNT_ID VARCHAR,
    SALES_REP_ID VARCHAR,
    OPTY_OPEN_DATE DATE,
    CLOSE_DATE DATE,
    PRODUCT_ID VARCHAR,
    QUANTITY INT,
    UNIT_PRICE FLOAT,
    LINE_ITEM_DISCOUNT FLOAT,
    FILE_NAME VARCHAR, 
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE PIPE BRONZE_DB.SALESFORCE.PIPE_SALES_ORDERS
AUTO_INGEST = TRUE
AS
COPY INTO BRONZE_DB.SALESFORCE.SALES_ORDERS
FROM (
  SELECT 
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    METADATA$FILENAME, 
    CURRENT_TIMESTAMP()
  FROM @BRONZE_DB.SALESFORCE.ST_S3_SALESFORCE/sales_orders/
)
FILE_FORMAT = BRONZE_DB.SALESFORCE.CSV_FORMAT_SALESFORCE;