----- view product opportunity ------
CREATE OR REPLACE VIEW GOLD_DB.SALESFORCE.PRODUCT_OPPORTUNITY_VW AS (
WITH DISCTIC_OPPORTUNITY AS (
SELECT 
OPPORTUNITY_ID, COUNT(1)
FROM SILVER_DB.SALESFORCE.SALES_ORDERS_FACT 
GROUP BY ALL
HAVING COUNT(1) > 2
)


SELECT FO.*
FROM SILVER_DB.SALESFORCE.SALES_ORDERS_FACT FO
INNER JOIN DISCTIC_OPPORTUNITY OP ON FO.OPPORTUNITY_ID = OP.OPPORTUNITY_ID);


------ Deal Complex  ---

SELECT *
FROM SILVER_DB.SALESFORCE.PRODUCT_CATALOG_DIM;
CREATE OR REPLACE VIEW GOLD_DB.SALESFORCE.PERFORMANCE_SALES_REP_COMPLEX_SALES AS (
WITH PRODUCT_COMPLEX AS (
SELECT 
F.*,
P.PRODUCT_NAME
FROM SILVER_DB.SALESFORCE.SALES_ORDERS_FACT F
LEFT JOIN SILVER_DB.SALESFORCE.PRODUCT_CATALOG_DIM P ON F.PRODUCT_ID = P.PRODUCT_KEY
WHERE PRODUCT_NAME IN ('Data Cloud - Base','Sales Cloud - Enterprise','Service Cloud - Unlimited')
)

SELECT
ORDER_ID,
SALES_REP_ID,
PRODUCT_ID,
PRODUCT_NAME,
DATEDIFF(DAY, OPTY_OPEN_DATE, CLOSE_DATE) AS DAY_CLOSE_SALE_2,
FROM PRODUCT_COMPLEX
ORDER BY SALES_REP_ID);