BEGIN TRANSACTION;
    --insert new customer from source
    INSERT INTO SILVER_DB.SALESFORCE.ACCOUNT_MASTER_DIM (ACCOUNT_KEY, ACCOUNT_ID,ACCOUNT_NAME,INDUSTRY,CUSTOMER_SEGMENT,CREATED_AT,STATUS)
        SELECT 
        BA.ACCOUNT_ID||CURRENT_DATE AS PRODUCT_KEY,
        BA.ACCOUNT_ID,
        BA.ACCOUNT_NAME,
        BA.INDUSTRY,
        BA.CUSTOMER_SEGMENT,
        CURRENT_TIMESTAMP() AS CREATED_AT,
        TRUE AS STATUS
        FROM BRONZE_DB.SALESFORCE.ACCOUNT_MASTER_EXT BA 
        LEFT JOIN SILVER_DB.SALESFORCE.ACCOUNT_MASTER_DIM SA ON BA.ACCOUNT_ID = SA.ACCOUNT_ID AND SA.STATUS = TRUE
        WHERE SA.ACCOUNT_ID IS NULL;



    -- update customer deletions from source
    CREATE OR REPLACE TRANSIENT TABLE SILVER_DB.SALESFORCE.ACCOUNT_MASTER_OUT_TMP AS (
    SELECT
    SA.*
    FROM SILVER_DB.SALESFORCE.ACCOUNT_MASTER_DIM SA
    LEFT JOIN BRONZE_DB.SALESFORCE.ACCOUNT_MASTER_EXT BA ON SA.ACCOUNT_ID = BA.ACCOUNT_ID
    WHERE BA.ACCOUNT_ID IS NULL);

    UPDATE SILVER_DB.SALESFORCE.ACCOUNT_MASTER_DIM SA
    SET  
    SA.DELETED_AT = CURRENT_TIMESTAMP,
    SA.STATUS = FALSE
    FROM SILVER_DB.SALESFORCE.ACCOUNT_MASTER_OUT_TMP SO 
    WHERE SA.ACCOUNT_ID = SO.ACCOUNT_ID AND  SA.STATUS = TRUE
    ;
COMMIT