----- view product opportunity ------
CREATE OR REPLACE VIEW GOLD_DB.SALESFORCE.PRODUCT_OPPORTUNITY_VW AS (
WITH DISCTIC_OPPORTUNITY AS (
SELECT 
OPPORTUNITY_ID, COUNT(1)
FROM SILVER_DB.SALESFORCE.SALES_ORDERS_FACT 
GROUP BY ALL
HAVING COUNT(1) > 2
)


SELECT FO.*
FROM SILVER_DB.SALESFORCE.SALES_ORDERS_FACT FO
INNER JOIN DISCTIC_OPPORTUNITY OP ON FO.OPPORTUNITY_ID = OP.OPPORTUNITY_ID);