BEGIN TRANSACTION;
    --update rows changes in source
    UPDATE SILVER_DB.SALESFORCE.PRODUCT_CATALOG_DIM SP
    SET SP.LIST_PRICE = BP.LIST_PRICE,
    STATUS = FALSE,
    DELETED_AT = CURRENT_TIMESTAMP
    FROM BRONZE_DB.SALESFORCE.PRODUCT_CATALOG_EXT BP
    WHERE  SP.PRODUCT_ID = BP.PRODUCT_ID AND SP.STATUS = TRUE AND SP.LIST_PRICE != BP.LIST_PRICE;

    -- insert new rows from source
    INSERT INTO SILVER_DB.SALESFORCE.PRODUCT_CATALOG_DIM (PRODUCT_KEY, PRODUCT_ID,PRODUCT_NAME,PRODUCT_FAMILY,LIST_PRICE,CREATED_AT,STATUS)
    SELECT 
    BP.PRODUCT_ID||CURRENT_DATE AS PRODUCT_KEY,
    BP.PRODUCT_ID,
    BP.PRODUCT_NAME,
    BP.PRODUCT_FAMILY,
    BP.LIST_PRICE,
    CURRENT_TIMESTAMP() AS CREATED_AT,
    TRUE AS STATUS
    FROM BRONZE_DB.SALESFORCE.PRODUCT_CATALOG_EXT BP 
    LEFT JOIN SILVER_DB.SALESFORCE.PRODUCT_CATALOG_DIM SP ON SP.PRODUCT_ID = BP.PRODUCT_ID AND SP.STATUS = TRUE
    WHERE SP.PRODUCT_ID IS NULL;

    --detect row deletions from source 
    CREATE OR REPLACE TRANSIENT TABLE SILVER_DB.SALESFORCE.PRODUCT_CATALOG_OUT_TMP AS (
        SELECT
        SP.*
        FROM SILVER_DB.SALESFORCE.PRODUCT_CATALOG_DIM SP
        LEFT JOIN BRONZE_DB.SALESFORCE.PRODUCT_CATALOG_EXT BS ON SP.PRODUCT_ID = BS.PRODUCT_ID
        WHERE BS.PRODUCT_ID IS NULL);

    UPDATE SILVER_DB.SALESFORCE.PRODUCT_CATALOG_DIM SP
    SET  
    SP.DELETED_AT = CURRENT_TIMESTAMP,
    SP.STATUS = FALSE
    FROM SILVER_DB.SALESFORCE.PRODUCT_CATALOG_OUT_TMP SO 
    WHERE SP.PRODUCT_KEY = SO.PRODUCT_KEY AND SP.STATUS = TRUE;

    DROP TABLE IF EXISTS SILVER_DB.SALESFORCE.PRODUCT_CATALOG_OUT_TMP;
COMMIT;