BEGIN TRANSACTION;
    --update rows changes in source 
    UPDATE SILVER_DB.SALESFORCE.SALES_REP_MASTER_DIM SS
    SET 
    SS.MANAGER_NAME = BS.MANAGER_NAME,
    SS.TERRITORY = BS.TERRITORY,
    STATUS = FALSE,
    DELETED_AT = CURRENT_TIMESTAMP
    FROM BRONZE_DB.SALESFORCE.SALES_REP_MASTER_EXT BS
    WHERE  SS.SALES_REP_ID = BS.SALES_REP_ID AND SS.STATUS = TRUE AND (SS.MANAGER_NAME != BS.MANAGER_NAME OR SS.TERRITORY != BS.TERRITORY);

    -- insert new rows from source
    INSERT INTO SILVER_DB.SALESFORCE.SALES_REP_MASTER_DIM (SALES_REP_KEY, SALES_REP_ID,REP_NAME,MANAGER_NAME,TERRITORY,HIRE_DATE,CREATED_AT,STATUS)
    SELECT 
    BP.SALES_REP_ID||CURRENT_DATE AS PRODUCT_KEY,
    BP.SALES_REP_ID,
    BP.REP_NAME,
    BP.MANAGER_NAME,
    BP.TERRITORY,
    BP.HIRE_DATE,
    CURRENT_TIMESTAMP() AS CREATED_AT,
    TRUE AS STATUS
    FROM BRONZE_DB.SALESFORCE.SALES_REP_MASTER_EXT BP 
    LEFT JOIN SILVER_DB.SALESFORCE.SALES_REP_MASTER_DIM SS ON SS.SALES_REP_ID = BP.SALES_REP_ID AND SS.STATUS = TRUE
    WHERE SS.SALES_REP_ID IS NULL;

    --detect row deletions from source 
    CREATE OR REPLACE TRANSIENT TABLE SILVER_DB.SALESFORCE.SALES_REP_MASTER_OUT_TMP AS (
        SELECT
        SS.*
        FROM SILVER_DB.SALESFORCE.SALES_REP_MASTER_DIM SS
        LEFT JOIN BRONZE_DB.SALESFORCE.SALES_REP_MASTER_EXT BS ON SS.SALES_REP_ID = BS.SALES_REP_ID
        WHERE BS.SALES_REP_ID IS NULL);

    UPDATE SILVER_DB.SALESFORCE.SALES_REP_MASTER_DIM SS
    SET  
    SS.DELETED_AT = CURRENT_TIMESTAMP,
    SS.STATUS = FALSE
    FROM SILVER_DB.SALESFORCE.SALES_REP_MASTER_OUT_TMP SO 
    WHERE SS.SALES_REP_KEY = SO.SALES_REP_KEY AND SS.STATUS = TRUE;

    DROP TABLE IF EXISTS SILVER_DB.SALESFORCE.SALES_REP_MASTER_OUT_TMP;
COMMIT;