BEGIN TRANSACTION;

    -- Create temporary table with new sales orders enriched with dimension keys
    CREATE OR REPLACE TRANSIENT TABLE SILVER_DB.SALESFORCE.SALES_ORDER_TMP AS (
    WITH ORDERS_NEW AS (
    SELECT BO.*
    FROM SILVER_DB.SALESFORCE.SALES_ORDERS_FACT SO
    RIGHT JOIN BRONZE_DB.SALESFORCE.SALES_ORDERS BO ON SO.ORDER_ID = BO.ORDER_ID
    WHERE SO.ORDER_ID IS NULL)

    ,PRODUCT_KEY  AS (
    SELECT 
    O.*,
    P.PRODUCT_KEY,
    FROM ORDERS_NEW O
    LEFT JOIN SILVER_DB.SALESFORCE.PRODUCT_CATALOG_DIM P ON O.PRODUCT_ID = P.PRODUCT_ID AND O.CLOSE_DATE >= P.CREATED_AT AND (O.CLOSE_DATE < P.DELETED_AT OR P.DELETED_AT IS NULL)
    )

    ,SALES_REP_KEY AS (
    SELECT 
    P.*,
    S.SALES_REP_KEY,
    FROM PRODUCT_KEY P
    LEFT JOIN SILVER_DB.SALESFORCE.SALES_REP_MASTER_DIM S ON P.SALES_REP_ID = S.SALES_REP_ID AND P.CLOSE_DATE >= S.CREATED_AT AND (P.CLOSE_DATE < S.DELETED_AT OR S.DELETED_AT IS NULL) 
    )

    ,ACCOUNT_KEY AS (
    SELECT 
    S.*,
    A.ACCOUNT_KEY
    FROM SALES_REP_KEY S
    LEFT JOIN SILVER_DB.SALESFORCE.ACCOUNT_MASTER_DIM A ON S.ACCOUNT_ID = A.ACCOUNT_ID AND S.CLOSE_DATE >= A.CREATED_AT AND (S.CLOSE_DATE < A.DELETED_AT OR A.DELETED_AT IS NULL) 
    ),

    CALCULATE_REVENUE AS (
    SELECT 
    A.*,
    (QUANTITY * UNIT_PRICE) AS TOTAL_REVENUE
    FROM ACCOUNT_KEY A
    )
    
    SELECT DISTINCT
    ORDER_ID,
    OPPORTUNITY_ID,
    ACCOUNT_KEY,
    SALES_REP_KEY,
    PRODUCT_KEY,
    OPTY_OPEN_DATE,
    CLOSE_DATE,
    QUANTITY,
    UNIT_PRICE,
    LINE_ITEM_DISCOUNT,
    TOTAL_REVENUE,
    TOTAL_REVENUE - LINE_ITEM_DISCOUNT AS NET_REVENUE
    FROM CALCULATE_REVENUE A);

    --Insert new sales into fact table 
    INSERT INTO SILVER_DB.SALESFORCE.SALES_ORDERS_FACT (
    SELECT 
    SOT.ORDER_ID,
    SOT.OPPORTUNITY_ID,
    SOT.ACCOUNT_KEY,
    SOT.SALES_REP_KEY,
    SOT.PRODUCT_KEY,
    SOT.OPTY_OPEN_DATE,
    SOT.CLOSE_DATE,
    SOT.QUANTITY,
    SOT.UNIT_PRICE,
    SOT.LINE_ITEM_DISCOUNT,
    SOT.TOTAL_REVENUE,
    SOT.NET_REVENUE
    FROM SILVER_DB.SALESFORCE.SALES_ORDER_TMP SOT 
    LEFT JOIN SILVER_DB.SALESFORCE.SALES_ORDERS_FACT SOF ON SOF.ORDER_ID = SOT.ORDER_ID
    WHERE SOF.ORDER_ID IS NULL
    );
COMMIT;