CREATE OR REPLACE ROW ACCESS POLICY SILVER_DB.SALESFORCE.RSL_TO_SALE_REP
AS (sales_rep_id STRING) RETURNS BOOLEAN ->
  EXISTS (
    SELECT 1 FROM SILVER_DB.SALESFORCE.SALES_REP_MASTER_DIM
    WHERE 
      (REP_NAME = CURRENT_USER() AND SALES_REP_ID = SALES_REP_ID)
      OR 
      (MANAGER_NAME = CURRENT_USER() AND SALES_REP_ID = SALES_REP_ID)
  )
  OR CURRENT_ROLE() = 'ACCOUNTADMIN' 
;

ALTER TABLE SILVER_DB.SALESFORCE.SALES_ORDERS_FACT
ADD ROW ACCESS POLICY SILVER_DB.SALESFORCE.RSL_TO_SALE_REP ON (SALES_REP_ID);